name: Testing and linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24

      - name: Install dependencies
        run: npm ci

      # ----- LINT -----
      - name: Lint niivue
        run: npm run lint:niivue

      # ----- UNIT TESTS -----
      - name: Unit tests
        run: npm run test:unit

      # ----- E2E TESTS -----
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Debug system info (Linux only)
        run: |
          echo "Free memory:"
          free -h || true
          echo "Disk space:"
          df -h || true

      - name: Run Playwright tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' \
          npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-ubuntu-latest
          path: playwright-report/
          retention-days: 30

      # ----- BUILD DEMOS -----
      - name: Build demos (github + docs)
        run: |
          npm run build:github
          npm run build:docs

      # ----- BUILD DOCUSAURUS -----
      - name: Build docusaurus
        env:
          PUBLIC_POSTHOG_KEY: ${{ secrets.PUBLIC_POSTHOG_KEY }}
          PUBLIC_POSTHOG_HOST: ${{ secrets.PUBLIC_POSTHOG_HOST }}
        run: |
          npm run build:niivue
          npm run build:docusaurus
